### ISSUE TITLE
Add Calendar and Discussion links to top-right of landing page

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/school-of-webmaking#121]
![Imgur](http://i.imgur.com/E1DLcvw.png)

**Comment by LauraHilliger** [comment]
@dirkcuys can you add to the start page? Icon + URL:
`<a href="https://www.google.com/calendar/embed?src=zythepsary.com_q6ugl9iepetabcp9eg9ltmruic@group.calendar.google.com&ctz=Europe/London"><i class="fa fa-calendar"></i> Calendar</a>
<a href="http://discourse.webmakerprototypes.org/category/"><i class="fa fa-comments"></i> Discussion</a>`

**Comment by dirkcuys** [comment]
Sure, added! baae543
