### ISSUE TITLE
Expand width of text in subpages

### ISSUE THREAD

**Issue by thornet** [mozilla/school-of-webmaking#127]
Pages like: http://training.webmakerprototypes.org/en/exploring/concepts/ have a lot of text, and the current margins don't take advantage of the whole page. 

Consider a wider layout for the text, perhaps more like http://training.webmakerprototypes.org/en/start-here/ for ease of reading.

**Comment by LauraHilliger** [comment]
@thornet I added line height, that should help a bit, but leaving this open to see if we should float the course image...

**Comment by fuzzyfox** [comment]
Depends on #217 to some degree maybe?

**Comment by LauraHilliger** [comment]
actually I'm going to close this. I think #217 will help, and we're talking about redesign and full integration anyway.
