### ISSUE TITLE
Make icons at bottom of pages bigger / clearer

### ISSUE THREAD

**Issue by thornet** [mozilla/school-of-webmaking#129]
At the bottom of pages like: 
http://training.webmakerprototypes.org/en/building/concepts/

There are links to Make, Resources, Discussion. 

The icons are small and the text a bit long / confusing. Maybe make the icons bigger and revise copy to:

<h1>What's next? </h1>

<h2>Concepts: Read more</h2> 

<h2>Make: Fun Digital Artifacts</h2> 

<h2>Explore: More resources</h2> 

<h2>Discuss: With Peers</h2>

**Comment by LauraHilliger** [comment]
Yes, I thought that header was ridiculous long too! I adjusted to say "Where to next?" and made the buttons bigger. These are dynamic, so if they change down here, they'd change at the top too, hence me just making them bigger and ignoring the copy revision.

We can reopen/refile this one when there is more devy power. 

Commit 43a8347
