### ISSUE TITLE
Concept pages improved readability formatting

### ISSUE THREAD

**Issue by thornet** [mozilla/school-of-webmaking#130]
Apart from the bug about page width, the text on the concept pages are hard to read, likely because of formatting. 

I don't have much design skills, but perhaps playing with line-spacing and clearer visual breaks between important sections would help to parse the page. 

Also, consider anchors to each section on a page, for easy referencing. 

This page, for example, seems to handle formatting well, especially is a well-formatted (although understandably different kind of) page as an example: http://party.webmaker.org/partners and also: https://webmaker.org/en-US/about

**Comment by LauraHilliger** [comment]
added line-height with commit ba3711f
