### ISSUE TITLE
Prioritize how to get help

### ISSUE THREAD

**Issue by thornet** [mozilla/school-of-webmaking#131]
On this page: http://training.webmakerprototypes.org/en/help/

Recommend leveling up / making <h1>:
- Participate in the Community [suggest rewrite as: "Ask a question in our discussion forum"]
- Write us on Twitter using the hashtag #teachtheweb. 
- Join a live session. We'll host live sessions each Monday at 16:00 UTC.

And have the remaining links lower.

**Comment by LauraHilliger** [comment]
Check those headers and file a new issue if you hate it! commit 6b51de2
