### ISSUE TITLE
"Social Hype" -> "Join the Discussion"

### ISSUE THREAD

**Issue by thornet** [mozilla/school-of-webmaking#132]
Suggestion renaming "Social Hype" on landing page to "Join the Discussion". Keep the Twitter widget and add an additional link to Discourse.

**Comment by dajbelshaw** [comment]
I'd suggest leaving things as they are, otherwise we elide two separate things. Have we had any feedback that it's confusing people? :-)

**Comment by LauraHilliger** [comment]
Hrm, it's easy enough to change the social feed title, but I'm a little worried that calling twitter AND discourse the "Discussion" might confuse people. Also, there's a link to Discourse in the navbar at the top. @thornet @dajbelshaw another suggestion for this title? (Social hype is lame, agreed!)

**Comment by dajbelshaw** [comment]
How about 'Follow along', 'Tell the world!', 'Keep up with the tweets' or
even just (ahem) 'Social media'?

**Comment by thornet** [comment]
Looks like "follow along" was added. Seems easy & smart. Marking as closed!
