### ISSUE TITLE
Copy header from training site to Discourse

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#135]
@dirkcuys I love the idea of making the header resemble PWYM's header by taking the header and nav from the training site and putting it in the discourse. Problem is, I don't know how to do this. 

http://i.imgur.com/pIiVsxz.png

(in this mock, I think if someone clicks on modules, they go to the Exploring concepts page. Should save us from too much hassle...)

**Comment by dirkcuys** [comment]
Hey @LauraHilliger, the header is not completely finished, but you can preview it by going to the discourse admin > select the customize tab > click on "Custom header + login button tweaks" > click preview below the text box.

Let me know what you think? Should we add the webmaker logo on top or would just the nav suffice?

**Comment by LauraHilliger** [comment]
I'd try to make it more like http://i.imgur.com/pIiVsxz.png because I, as a user, would actually expect that clicking on the logo takes me to the website (like it does on PWYM), not to the Discourse start page.

**Comment by dirkcuys** [comment]
That makes sense. Let me see if I can pull that off. Otherwise I may need to pull in @ercchy for her CSS wizardry :)

**Comment by dirkcuys** [comment]
Please have a look again. I think we just need to update the logo and then we are set?

**Comment by LauraHilliger** [comment]
I fiddled a bit with the CSS and it looks good :) The only thing I couldn't seem to do was get the little comments icon in there, but that's just aesthetics. Closing in favor of not rabbit holing! THANKS @dirkcuys
