### ISSUE TITLE
Add training RID to all webmaker links

### ISSUE THREAD

**Issue by fuzzyfox** [mozilla/school-of-webmaking#139]
A fairly quick (temp) fix so that we can track how many people signup to webmaker because of training (via thimble/popcorn/whatever) would be to add a RID to any urls pointing to _.webmaker.org/_

My proposal to do this fast w/o changing all the content, and digging for links, is to add a small JS method that looks for links on the page, and appends where needed.

RIDs: https://wiki.mozilla.org/Webmaker/Maker_Party/referrer_api

**Comment by LauraHilliger** [comment]
submit pull request?

**Comment by dirkcuys** [comment]
Maybe we can grep/awk the link to include the RID, we can use the same regex to get the links in the content?

EDIT: although, having looked at https://wiki.mozilla.org/Webmaker/Maker_Party/referrer_api, may be a good idea to use JS since all future links would also get the RID
