### ISSUE TITLE
Add timing info to intro tag line

### ISSUE THREAD

**Issue by thornet** [mozilla/school-of-webmaking#144]
On the landing page, we could add more info so people know what's on offer right from the start. 

Suggested revised copy: 

"Join anytime. Learn at your own pace. Connect with our global community helping one another teach web literacy, digital skills and open practices. Learn how to #TeachTheWeb."

Feels like another paragraph somewhere prominent on the landing page would help:

Webmaker Training is part of Mozilla's non-profit mission to promote openness, innovation and opportunity on the Web. This training is free to use and open-source. It's built and moderated by expert volunteers around the world."

**Comment by LauraHilliger** [comment]
commit 45e4670
