### ISSUE TITLE
Add Tabzilla

### ISSUE THREAD

**Issue by thornet** [mozilla/school-of-webmaking#145]
Realized the training site has little mention of Mozilla as a brand. 

Suggest adding Tabzilla or another prominent wordmark (maybe change main nav to "Made by Mozilla and P2PU" or something).

**Comment by LauraHilliger** [comment]
added Tabzilla via commit 1c2b341 
@fuzzyfox - this looks odd, not lined up, no shadow. Can you fix?

**Comment by fuzzyfox** [comment]
@LauraHilliger R? https://github.com/p2pu/school-of-webmaking/pull/166

**Comment by LauraHilliger** [comment]
w00t!! thanks @fuzzyfox
