### ISSUE TITLE
Uplevel "run a NN Maker Party"

### ISSUE THREAD

**Issue by ghost** [mozilla/school-of-webmaking#198]
Main CTA on this page should be running a MP: 

https://training.webmakerprototypes.org/en/net-neutrality/make/

can lighten language to be about exploring the topic with friends and family. should also be clear that they can just use existing teaching kit rather than needing to make a new one.

**Comment by ghost** [comment]
Probably better to call "teach someone NN" instead of run an event.

**Comment by LauraHilliger** [comment]
50aa9c891d
