### ISSUE TITLE
Switch URL from training.webmaker.org to training.mofostaging.net

### ISSUE THREAD

**Issue by jbuck** [mozilla/school-of-webmaking#22]
Could you change the CNAME from training.webmaker.org to training.mofostaging.net? That way no-one will stumble upon it, and think it's ready for public consumption. When it's ready to go to production, we can flip the DNS to point back at training.webmaker.org.

**Comment by dirkcuys** [comment]
Sure! Done! 98630ea7b709d77b4e02a81557362ab0ea4892e1
