### ISSUE TITLE
Building Module Peer Learning Design

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#28]
Live Component draft 1: https://laura.makes.org/thimble/building-for-participatory-learning-teaching-kit

Desc: The Building Online module should be heavily focused on the principles of codesign to help people build teaching kits and activities. 

There should be strong underpinnings of the sort of meta definition of the web (e.g. it's not just a tool or platform it is knowledge documented, humanity in an open format, the collective mind connected, THE WEB) and curriculum design underneath.

We should try to outline things like  Ideation, Outlining Objectives, Building in collaboration, Paper Prototyping...etc

Conversation from Trello:
--@katbraybrooke is amazeballs at the codesign process, and I want to teach that alongside the curriculum design process. I think the three of us can really make this (and all the other) modules super kick ass. Kat's also epically awesome at making content interesting/entertaining, so I think stuff we learn while building this piece out will transfer to the other modules well :)

--This is a nice exercise, maybe we can build it in: http://www.clawrence.org/2014/01/09/bulldogskin/

--We should build remix more explicitly in: https://webmaker.org/en-US/standard/building#remixing and add build paper prototyping into teaching kit piece of Building Online

--from Kat: took a look, and i think we might need to chat about the details of this more for me to totally "get" it - at moment it looks very much like an in-person training session, but it'll be online so how do we reconcile that? (will ask you more tomorrow in our chat in any case!) woot.

Ahhh yes @katbraybrooke there are two streams at play here, the online content for anyone, anytime, anywhere and a supporting teaching kit for people who want to teach the learning objectives to real people in an event. We're both training the trainer via the online as well as giving people the ability to train the trainer offline by providing them with modified content for an offline environment.

As I mentioned to @vanessagennarelli1, the learning objectives in both environments are the same.

from Kat: Cheers. Update: I'm going to focus on building paper prototype templates and remixing this kit with "remix" in mind (haha) and making it more clear this is the in-person version of the module today/tomorrow using @webmaker account. Will report back as I do it for each part!

**Comment by mozzadrella** [comment]
Hey @LauraHilliger and (and Kat) just a quick update--I'm chewing on some exercises for co-design and paper prototyping based on this feedback.

**Comment by mozzadrella** [comment]
Bonjour @LauraHilliger: Did some thinking on this yesterday. 

# Add Design Process to Building

So based on Kat's feedback and yours, think we should add another H1 to the unit on "The Design Process", including:
-IDEO's design thinking for educators process
![screen shot 2014-03-29 at 10 51 52 am](https://cloud.githubusercontent.com/assets/1874003/2558623/be66bfb4-b751-11e3-8523-a249f0de7d2e.png)

Focus on Community Design
"Through a series of mini-charettes, Design Thinking Hawaii has collected the needs and interests of learners, teachers, and families and engaged the larger community to imagine new solutions that could help the school be more effective. The adopted plan captured the community’s priorities in new content and structures, and Complex Area Superintendent Lea Albert is enabling the school and community to prototype and iterate core curriculum, character education, and support services. This is the first public-school model in Hawaii to co-design its offerings with community, targeting systemic educational problems."
http://www.designthinkingforeducators.com/design-examples/

Iteration for Learning
- Why is iteration important? Integrate peer feedback and iterate to reflect.
- Reflection in Action: 
  The practitioner allows himself to experience surprise, puzzlement, or confusion in a situation which he finds uncertain or unique. He reflects on the phenomenon before him, and on the prior understandings which have been implicit in his behaviour. He carries out an experiment which serves to generate both a new understanding of the phenomenon and a change in the situation. (Schön 1983: 68)
  http://infed.org/mobi/donald-schon-learning-reflection-change/
  http://llk.media.mit.edu/courses/readings/schoen-interview.pdf
- Iteration introduces distance between creator and piece--able to see it more clearly.

# Flesh Out Peer Networks H1 to Include Networks of Making + Curation

-User generated learning: "User-generated learning is learning that is acquired through active curation, reflection, and contribution to a self-selected collaborative space. This basically means that user-generated learning is something you do, not something you get." 
http://www.usergeneratedlearning.com/what-is-ugl/
-Add Ben Schniederman's "Relate, Create, Donate" framework. http://www.cs.umd.edu/hcil/relate_create_donate/

# Frame the 2nd Make In Terms of Paper Prototyping _and_ Feedback Mechanisms

# Frame the 3rd "Make" in the Building Module a Curation Make
- Collect the inspiration for your first make into a Storify, a Pinterest Board, or a gallery via Thimble

# Frame a 4th "Make": Redesign a unit from your classroom using a Community Design process.

# 5th Idea for a Make: Remix to Reflect
- Iterate on one of your makes. 

@LauraHilliger let's connect on Monday--I was out Friday, but I've been chewing!

**Comment by LauraHilliger** [comment]
Whoa! This sounds really good. The only thing I would caveat is that in the end, we want people to be making teaching kits in this module. 

(See learning objectives in the kit for this module: https://laura.makes.org/thimble/building-for-participatory-learning-teaching-kit )

So perhaps we can frame the makes to do both the paper prototyping but also digital documentation? Or is the digital part at the end?

I really like the "redesign a unit" bit, but it's important to note that not everyone in our audience has a classroom or regular teaching job, some are open sources wanting to teach for the first time...Now you know why it's so hard to pare down the number of make options!!

@mozzadrella definitely want to sync with you today, but am on a plane until around 5pm (11am). I'll try to ping you when I get to the hotel (sending you an email)!

**Comment by mozzadrella** [comment]
Hey @LauraHilliger made updates to the "Make" https://github.com/p2pu/school-of-webmaking/blob/gh-pages/_posts/2001-01-02-make.md and the "Explore" sections http://training.mofostaging.net/building/explore/ I'm not 100% thrilled with them, but plan to keep chewing (but was mindful of the feedback above)

**Comment by mozzadrella** [comment]
![screen shot 2014-04-14 at 3 52 16 pm](https://cloud.githubusercontent.com/assets/1874003/2700212/8e9f825e-c410-11e3-9149-25d2b86eb653.png)
![screen shot 2014-04-14 at 3 51 59 pm](https://cloud.githubusercontent.com/assets/1874003/2700213/9066ae82-c410-11e3-8601-66b71429a832.png)

**Comment by mozzadrella** [comment]
![screen shot 2014-04-14 at 4 23 06 pm](https://cloud.githubusercontent.com/assets/1874003/2700438/cdf31572-c412-11e3-9811-4b004faa72cd.png)

**Comment by mozzadrella** [comment]
Tweaked the makes here based on @LauraHilliger's feedback. OK to close out?

**Comment by LauraHilliger** [comment]
Made some light edits, but otherwise AWESOMESAUCE
