### ISSUE TITLE
Facilitating Module Peer Learning Design

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#29]
Live component: https://laura.makes.org/thimble/facilitating-participatory-learning-teaching-kit

This is the facilitating module so the IRL is a big deal, however, we should use the live agenda to influence what we can teach in an online environment...

We can build practical activities around playtesting + beginning organizing and facilitating events into the content.

**Comment by LauraHilliger** [comment]
I'm pulling out the Reflection questions to fix issue #83 :

# Reflecting on our experiences and creations leads us down the path to life-long learning.

Write or make your reflections and share them with the [Webmaker Community](http://discourse.webmakerprototypes.org/).
- Who do you imagine your audience to be? Can you reach them in #teachtheweb? How can #teachtheweb help you reach them elsewhere? With whom do you most need to playtest your work?
- How can your #teachtheweb work connect to the rest of your calling?
- How is #teachtheweb a playtest for expanding your teaching?
- How do we situate what we've learned about web authoring and teaching the web in our work with other learners?
- How can you help your audience  and yourself cultivate the awareness to identify and report on "bugs" in teaching and learning?
- Why does encouraging feedback from your audience lead to improved learning designs

**Comment by LauraHilliger** [comment]
@mozzadrella  I added lots of text and thoughts from Chad Sansing, so hopefully this is easier for you now!

**Comment by mozzadrella** [comment]
![screen shot 2014-04-28 at 5 24 29 pm](https://cloud.githubusercontent.com/assets/1874003/2823140/a1fad00e-cf1b-11e3-8d63-3bb0823b6365.png)
![screen shot 2014-04-28 at 5 24 18 pm](https://cloud.githubusercontent.com/assets/1874003/2823139/a1fa7762-cf1b-11e3-8327-a98ff4746514.png)
![screen shot 2014-04-28 at 5 24 06 pm](https://cloud.githubusercontent.com/assets/1874003/2823141/a1fbecfa-cf1b-11e3-8dc6-17a4cc2af764.png)
