### ISSUE TITLE
Connecting Module Peer Learning Design

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#30]
Build out run an event + engagement module, eg the connecting back into the global community pieces. I think social media stuff + maker party are a big pieces here, as well as local and global networking.

**Comment by LauraHilliger** [comment]
add social media advice as well as "contact journalists" to the connecting module.

**Comment by LauraHilliger** [comment]
@mozzadrella here too, I added thoughts from Chad Sansing, so you have more to work with.

**Comment by LauraHilliger** [comment]
we should add a sentence or two about kindred spirits in local areas, basically how to find your local crew - eg python groups, nerdy meetups, maker spaces, hackerspaces – point people to resources.

**Comment by LauraHilliger** [comment]
maybe also a sentence or two about trolls and how to get thick skin while connecting in online communities? Doesn't seem necessary for Mozilla or P2PU communities, but trolls pop up in the digital so maybe telling people not to get disencouraged is a good idea?

**Comment by mozzadrella** [comment]
Hey @LauraHilliger I'm still chewing on the trolls pieces, but added quite a bit about building communities and cultures of participation.

@dirkcuys none of my commits seem to deploy :(

**Comment by dirkcuys** [comment]
@mozzadrella don't worry, they are deploying, just taking a while (+- 10min)
