### ISSUE TITLE
Jekyll template

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#31]
from Trello:
--support for more than 1 course in 1 repository - we can split the courses, but with vanilla github pages that will require different domain names (or sub domains)
--Maybe setup with LESS for ttw specific CSS. Not 100% sure since it will require using LESS when customizing the course if it gets fork
--1st pass integration of Makerstrap.

**Comment by dirkcuys** [comment]
I think this is more or less ready. We can address the things that isn't right atm in separate issues.
