### ISSUE TITLE
Badges for Teach the Web Modules

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#34]
We need the criteria, visual design and descriptions for badges around the Webmaker Training content. Badges should work in both the online and offline environment. We should coordinate with Doug and others on the TTW team to make sure the training badges plug into the overarching ecosystem of webmaker badges.

fyi we have 1 badge for this that is kind of the überbadge (we can redesign the look, of course): http://blog.webmaker.org/mentor

**Comment by LauraHilliger** [comment]
@mozzadrella would like to know if you are on board with this badges plan:
4 badges that anyone can apply for over the course of the course
    making as learning (exploring)
    OER content / creating learning experiences (building)
    playtesting / feedback (facilitating)
    openness practices (connecting)

We have our defined badges for people to earn, but also encourage them to make their own. Currently, I do not think they will actually be able to upload and ISSUE their self made badges through the Webmaker install of BadgeKit until AFTER they are badged as Webmaker Mentors. But I still think we can scope these four badges, what do you think @mozzadrella

**Comment by dajbelshaw** [comment]
I love that you're thinking about badges for testing. However, I'd hold off for a couple of reasons:
1. There's lots of moving pieces and no direct 'ownership' / project management of Webmaker badges right now. There may be a strategy somewhere that this conflicts with.
2. The more granular you make badges (and these, by definition, are more granular than the Mentor badge) then the more you need to talk about badge/learning pathways. And we haven't done any of that yet.

So I would suggest proposing these badges for later in the year. AFAIK the current flow in terms of what we're prioritizing each depend on the stage before:

Super Mentor --> Mentor --> Web Literacy competency (Remix)

What are your thoughts, @LauraHilliger & @mozzadrella? :-)

**Comment by LauraHilliger** [comment]
So, @dajbelshaw and I are were talking about how the Mentor badge criteria needs to change, and then this will be the badge people get by participating in the training: http://blog.webmaker.org/mentor

**Comment by LauraHilliger** [comment]
As discussed @mozzadrella here are the Super Mentor and Mentor badges:

Mentor: http://blog.webmaker.org/mentor
Super Mentors:
https://blog.webmaker.org/super-mentor-badges
https://wiki.mozilla.org/Webmaker/Super_Mentors
