### ISSUE TITLE
Module page wireframes

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#35]
We've mapped basic architecture: https://teach.etherpad.mozilla.org/ttw-splash
and should review how/if inner page structure needs to change.Depends on @dirkcuys and @mozzadrella seeing change to the jekyll structure now that the user stories have become more useful.

**Comment by LauraHilliger** [comment]
Kat and I had a conversation, her feedback:
what if each module looked like THIS? http://reports.p2pu.org/reports/assessment_on_the_web/part_1/index.html - i.e., big text, obvious headings, navigation on _top_ instead of on side.

and I was thinking that maybe we could match the webmaker site with the subnavigation something like (I threw this together quickly, playing with colors..I like to make things :) http://i.imgur.com/Rt5Pza5.png

**Comment by LauraHilliger** [comment]
updated this image and filed a bug with Cassie for advice: http://i.imgur.com/h9A73qv.png
https://bugzilla.mozilla.org/show_bug.cgi?id=985913

**Comment by mozzadrella** [comment]
I think the template looks just great. My only concern is with the word
"Modules"--it's a bit top-down? I'll do some thinking about alternatives...

On Thu, Mar 20, 2014 at 8:28 AM, Laura Hilliger notifications@github.comwrote:

> updated this image and filed a bug with Cassie for advice:
> http://i.imgur.com/h9A73qv.png
> https://bugzilla.mozilla.org/show_bug.cgi?id=985913
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/p2pu/school-of-webmaking/issues/35#issuecomment-38160817
> .

## 

Vanessa Gennarelli
mozzadrella.me
@mozzadrella

**Comment by LauraHilliger** [comment]
So i built this nav and merged the pull request. @dirkcuys you should most definitely check that I didn't screw up my coding. @CassieMc gave some great feedback, and i've implemented most of it:

https://redpen.io/efvo9m

**Comment by LauraHilliger** [comment]
closing as a duplicate/precursor of: https://github.com/p2pu/school-of-webmaking/issues/36
