### ISSUE TITLE
Discuss Landing Page/Section for each module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#36]
from Trello:

--I'm kind of thinking we need a landing page for each module? One that explains what the module is and gives people the option of "I want to take this course" or "I want to teach this course" (with a link to the module teaching kit). Or maybe it's about the design of the "Concept" piece, where we put guided information about the module above the articles? What do you guys think?

--from Kat:  I was also thinking of a very simple landing page for each module, which lays out the learning pathway before folks get started/overwhelmed - one path leading to the mixed online format, one path leading to the teaching kit which helps them facilitate the whole 8-9 hr module with a group. Ignore the fonts and colours (they're not Makerstrap or anything) but this is an illustration of that simple-pathway-button idea. Thoughts?
![buildmodule1](https://f.cloud.github.com/assets/539017/2407809/024eee2a-aa93-11e3-9ce1-cd3653b9fb8e.jpg)

**Comment by keyboardkat** [comment]
Yo guys, I exist on Github again! 

Interested to hear what you think re: the sort of pathway I "jankily" wireframed above.

**Comment by LauraHilliger** [comment]
We were talking about it today, and we were thinking it might confuse people who are coming to training to be trained. So I think we'll downlevel the live agenda BUT we <3 a more visual approach and definitely are wanting to think through what landing in a module looks like. Also, your mockup is purdddy.

**Comment by keyboardkat** [comment]
Hmm, makes sense. Altho I do still think that drawing a clear line between online/offline portions would be good, especially given diff folks will have different pathways for this. Looking forward to the visuals you guys come up with!

**Comment by LauraHilliger** [comment]
@dirkcuys @mozzadrella do you have ideas on breadcrumbing or using the content to show where you are? You hit "Modules" and pick one, and then you're lost.

I think these two issues are the same, FYI, so I'm closing the other: https://github.com/p2pu/school-of-webmaking/issues/35
