### ISSUE TITLE
User Signups for courses

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#37]
--I'm asking our engagement team to begin thinking about how the BSD setup needs to be so that we know which forms need to be implemented where. I'm also wondering if we can mod the mechanical mooc piece to work with BSD instead of mailgun. 

Figure out Signup strategy on training.webmaker.org discussion in:
https://bugzilla.mozilla.org/show_bug.cgi?id=978148

**Comment by LauraHilliger** [comment]
Just tracking a thought: Brett and I were talking about the need for Webmaker to know a bit more about our users. He suggested that maybe there's a way to have the user flow be like: user signs up to webmaker via training > they're "marked" as training users > we see the joined in DATE, they are give a tag (cohort1) > sent specific engagement list...

Then we sort of talked about how that wouldn't work because users who sign up and then navigate to training may be lost, and it doesn't solve the "Holy crap we have a lot of different lists!" issue...

**Comment by LauraHilliger** [comment]
Update, we'll be covering this in a call on Friday and should have decisions made so we can close this ticket :)

**Comment by dirkcuys** [comment]
hey @LauraHilliger have you settled on a final method for signup?

**Comment by LauraHilliger** [comment]
We'll use this signup form for now https://sendto.mozilla.org/page/s/get-updates-about-webmaker-training
