### ISSUE TITLE
Test/Seed production build of Discourse

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#43]
We should have some content and conversations in Discourse before massive training push, so it feels alive and so we can test categories, tags, etc

**Comment by dirkcuys** [comment]
Agreed. I was thinking that we should create a category for every course and a topic in the category for every piece of content in the course. 

http://training.mofostaging.net/exploring/explore/ would have the category 'exploring' for discussion about the whole module and there would be a single topic for the discussion about that specific page. http://training.mofostaging.net/exploring/make/ would have the same category, but there would be a separate topic for it.
