### ISSUE TITLE
Create a Make Prompt in Connecting Module on defining "openly networked"

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#54]
Would be awsm to have curated conversations around "openly networked" and build a collaborative definition of that. Perhaps we can use it as a make prompt or discussion prompt for discourse.

**Comment by mozzadrella** [comment]
+1 I'll break this off.

**Comment by mozzadrella** [comment]
This one is for you, @LauraHilliger 
![worksheet](https://cloud.githubusercontent.com/assets/1874003/2749872/90d53b28-c82e-11e3-94f0-5f0519619131.png)

**Comment by mozzadrella** [comment]
![screen shot 2014-04-19 at 10 05 59 pm](https://cloud.githubusercontent.com/assets/1874003/2749916/ffbe14ea-c835-11e3-99b2-813113579c72.png)

**Comment by mozzadrella** [comment]
![screen shot 2014-04-19 at 11 06 36 pm](https://cloud.githubusercontent.com/assets/1874003/2749933/d4441500-c838-11e3-9083-2689e605ff02.png)

**Comment by mozzadrella** [comment]
![screen shot 2014-04-19 at 11 30 12 pm](https://cloud.githubusercontent.com/assets/1874003/2749974/3c39a0b4-c83c-11e3-94ee-f4555534ad66.png)

**Comment by mozzadrella** [comment]
![screen shot 2014-04-19 at 11 49 35 pm](https://cloud.githubusercontent.com/assets/1874003/2749996/f262ba36-c83e-11e3-92c1-34651267a7cd.png)

**Comment by mozzadrella** [comment]
![screen shot 2014-04-21 at 2 46 26 pm](https://cloud.githubusercontent.com/assets/1874003/2757531/4b108f68-c985-11e3-978c-7dbdde53644f.png)

**Comment by LauraHilliger** [comment]
wow, this just keeps getting better and better. The Whole Child activity, there's this: https://jeannie.makes.org/thimble/teaching-the-whole-child, which is the original author, but maybe I put that in our new template? Hrm...sending you an email :)
