### ISSUE TITLE
Get Training into Webmaker Prototype world (DNS)

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#55]
The Product team has created a space for us to host training for the foreseeable future.

They're working in this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=983729

And have this github Repo
https://github.com/mozilla/prototypes.webmaker.org

We'll have to change the DNS, but I'm not sure, based on what's here, if they're ready. Maybe @Fuzzyfox can help

**Comment by fuzzyfox** [comment]
I think it is a little early. The process is still being figured out... will update this as I know more.
