### ISSUE TITLE
Remove "edit in github" button (or hide it)

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#56]
first reaction from the community in the teachtheweb call was "What's this for"... @mozzadrella  maybe we should remove it or hide it? Can you still edit without it?

**Comment by dirkcuys** [comment]
I had to fix some discourse stuff and the github edit buttons clashed with it, so I went ahead and removed them. @mozzadrella if editing is now too difficult for you, let me know and we can hide the github link somewhere where it doesn't catch the eye that much.
