### ISSUE TITLE
Refresh Make page layout

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#65]
I think the Make pages could match webmaker galleries more, so that it's easy for people to feel invited to MAKE (instead of read). See here:

http://i.imgur.com/LX9UU1P.png

Not sure if 4 would fit, I know galleries are included in MakerStrap, but I don't know how to separate the make options out of the markdown to experiment with a better layout.

**Comment by LauraHilliger** [comment]
Found this from @flukeout : https://flukeout.makes.org/thimble/dat-gallery @dirkcuys thoughts?

**Comment by dirkcuys** [comment]
We could use https://github.com/mozilla/makeapi-client to dynamically pull content from the Make API. Would there be specific tags or queries that you wish to display?

**Comment by LauraHilliger** [comment]
I have admin access and could tag with something specific if need be. If you set this up, I can take the "Make" pages, make them into tutorials + resources in Webmaker, tag them with "webmaker:makeprompt-1", and then we can pull them in dynamically! 

Updating a bug to clarify that tagging: https://bugzilla.mozilla.org/show_bug.cgi?id=974321

**Comment by dirkcuys** [comment]
Just to update - we've integrated the MakeAPI, but currently there is still some issues with the CSS that we need to fix. See http://training.webmakerprototypes.org/en/building/make/

**Comment by dirkcuys** [comment]
I just came across this: https://github.com/mozilla/MakeAPI-Gallery - Seems to be the original CSS + JavaScript used in the example from @flukeout?

**Comment by dirkcuys** [comment]
note: need to fix funny layout, see http://training.webmakerprototypes.org/en/building/make/

**Comment by dirkcuys** [comment]
The fix is not perfect, but it should display properly now.
