### ISSUE TITLE
discourse blocking posts with similar URLs

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#66]
We'll be using and reusing our user.makes.org/ URLs, and with Chad, discourse was blocking him:

http://ttw-discourse.mofostaging.net/t/new-user-chadsansing-posts-blocked-for-repeated-links/23

@dirkcuys can you see this error message? Maybe we have to level up new users right away?

**Comment by dirkcuys** [comment]
@LauraHilliger yes, I also saw that message. We can tweak the user settings, I'll look to see if we can whitelist a URL for links?

**Comment by dirkcuys** [comment]
Indeed, there is a setting for this called `white_listed_spam_host_domains`

**Comment by LauraHilliger** [comment]
yay! so makes.org and then we can close this! ISSUE CLOSING IS THE BEST THING EVER :D

**Comment by dirkcuys** [comment]
I added makes.org and *.makes.org
