### ISSUE TITLE
remove html from title on module pages

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#67]
just noticed that the icons HTML shows up in the title element on module pages. See this screenshot:

http://i.imgur.com/FixasmE.png

**Comment by dirkcuys** [comment]
@LauraHilliger will it be an acceptable solution to add an extra field to the jekyll front matter called icon?

**Comment by LauraHilliger** [comment]
sounds like a good solution, especially if it can be blank (b.c I LOVE the icons, but am not sure they'll get through review)

**Comment by dirkcuys** [comment]
I found an easier way to clean the titles while keeping the HTML in the title. We can still separate them if needed, but I prefer less moving parts.

**Comment by dirkcuys** [comment]
Ok, HTML is gone from window titles!
