### ISSUE TITLE
make discourse link more obvious

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#68]
people are having a hard time finding it at the bottom of the articles. Need to discuss how it affects the design of pages. If we embed the rest of the discourse category, it makes sense to stay at the bottom. If we are linking out (as we currently are) it might make sense to put it in the nav?

**Comment by LauraHilliger** [comment]
After talking with @mozzadrella we think the best thing to do is to link from the subnav on each module page. @dirkcuys BEWARE - I deleted the "courses" category and moved each module category up (e.g. so they're no longer subcategories). @mozzadrella we'll need to double check discourse links throughout, as you noted! I'm still fiddling with organization, but this structure for each of the modules will stay: http://discourse.webmakerprototypes.org/category/exploring

**Comment by dirkcuys** [comment]
@LauraHilliger I added the discourse link to the subnav - please have a look and let me know if that works?

**Comment by LauraHilliger** [comment]
LOOKS GREAT! Closing this ticket (and opening a new one for a final once over on subnav. Later modules have extra subnav, will correct!)
