### ISSUE TITLE
Resources for Building Module

### ISSUE THREAD

**Issue by mozzadrella** [mozilla/school-of-webmaking#70]
So I was thinking Kat might have some stellar resources collected on paper prototpying and iteration.

Also, I was thinking about making the folks who share their work into a gallery of faces and descriptions--I can do that easily. But would give some human context to what these folks do.

What say you, @LauraHilliger?

**Comment by LauraHilliger** [comment]
I know @katbraybrooke is working on a couple paper prototyping templates, so we will be able to include those (I think she was aiming to have them finished this week). And I've designed some activities around brainstorming and ideation, which we can also remix for online learning (they're in the live agenda: https://laura.makes.org/thimble/building-for-participatory-learning-teaching-kit )

I LOVE the idea of the gallery!  How were you envisioning this?

@FuzzyFox built the "Community Quilt" https://mozilla.makes.org/thimble/web-we-want-quilt_ 
I wonder if that is useful? Could remix?

**Comment by fuzzyfox** [comment]
@LauraHilliger A better Community Quilt is under development over at https://github.com/fuzzyfox/supportopen. If you do go that route I'd use the contents of that repo as a base. ;)

**Comment by mozzadrella** [comment]
Pulled out these resources but used several of them:

## Webmaking as Learning
- http://www.hybridpedagogy.com/Journal/files/Play_Games_Gamification_Active_Learning.html
- http://www.hybridpedagogy.com/Journal/files/Unmapping_the_Terrain_of_Digital_Pedagogy.html
- http://carlacasilli.wordpress.com/2013/03/25/badge-pathways-part-1-the-paraquel/
- http://carlacasilli.wordpress.com/2013/04/28/badge-pathways-part-2-the-quel/
- http://michellethorne.cc/2013/05/webmaker-train-the-trainer/
- http://mako.cc/academic/hill_monroy-remixing_dilemma-DRAFT.pdf
- http://issuu.com/yollocalli/docs/homagoguidebook
- http://ds106.us/ & http://magicmacguffin.info/
- http://www.youtube.com/watch?v=KTBHYWFm8zw&list=UUCZOP8v5eEQ1euRMP0ljtfw&index=125
- http://www.youtube.com/watch?v=wJuQLOKa__w&list=UUCZOP8v5eEQ1euRMP0ljtfw&index=126
- http://www.youtube.com/watch?v=hdL0hCnGJ04&list=UUCZOP8v5eEQ1euRMP0ljtfw&index=127
- http://vyclone.com/ Great app for collecting and aggregating video if multiple people are recording different angles/elements of a making event.
- Beetham, H. (2010) Review and Scoping Study for a Cross-JISC Learning and Digital Literacies Programme: Sept 2010, JISC [online]. Available at http://www.jisc.ac.uk/ media/documents/ programmes/ elearning/ DigitalLiteraciesReview.pdf
- http://its.ucsc.edu/security/top10.html "Top 10 List" of Good Computing Practices
- A commercial for Level 3 Communications, but also a basic intro to Cyber Security http://www.youtube.com/watch?v=8PG8fbUgf-Y
  http://www.youtube.com/watch?v=COU5T-Wafa4 
- How to Make Secure Passwords, Mozilla Security Center: http://www.mozilla.org/security/
- Totally Awesome, Interactive Do not Track Trailer http://t.co/mOUoUCeA3E

**Comment by mozzadrella** [comment]
@LauraHilliger made a ton of updates here based on your feedback about the learning goals of the section. Hopefully we're very close :) http://training.mofostaging.net/building/resources/

**Comment by mozzadrella** [comment]
I <3 the photos added to Building @LauraHilliger
