### ISSUE TITLE
Create page for "Run a Training"

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#73]
We need to add a new page to the site, the place where folks can find information on how to fork the modules and/or run a live version of the training. I have agendas for the IRL, which are currently within each module. 

I'm getting some advice from Lainie and am filing this so @dirkcuys can make a page (in global nav) with the caveat that we haven't decided 100% on the naming.

**Comment by LauraHilliger** [comment]
ok, let's call it "Host a Training"

**Comment by dirkcuys** [comment]
Added the link and a blank page: 46b36d6f591033bea572e4dcf680e6c89a69426f
