### ISSUE TITLE
fix Exploring module URL

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#75]
all the other modules look like: http://training.webmakerprototypes.org/facilitating/explore/
but Exploring is http://training.webmakerprototypes.org/exploring/01-explore-concepts/

we should fix that :)

**Comment by LauraHilliger** [comment]
I mean, the "01-explore-concepts" should just be "explore"

**Comment by dirkcuys** [comment]
Should be fixed in this commit: 524567ecdadcc93f212b57b139c20ab3f79d1274

**Comment by dirkcuys** [comment]
Oh, wait, it will still be explore-concepts. Should it be http://training.webmakerprototypes.org/exploring/explore/ or http://training.webmakerprototypes.org/exploring/concepts/ ?

**Comment by LauraHilliger** [comment]
I think it should match the subnav: http://training.webmakerprototypes.org/exploring/concepts/ which means it should change on all the others too (they all say "explore" still)

**Comment by dirkcuys** [comment]
Updated! 6e431ff94643...5fa16568ee1f
