### ISSUE TITLE
point user to discourse instead of G+

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#78]
@mozzadrella I noticed that we're asking users to use G+ in the content, shouldn't we be prompting them to discuss and share their makes in Discourse instead? 

We need to figure out how to explain the difference b/w discourse and G+ to our community...

**Comment by LauraHilliger** [comment]
http://discourse.webmakerprototypes.org

**Comment by mozzadrella** [comment]
Totally. I will do today.

Working on integrating the other pieces by Friday--any other ideas /
feedback before then?

Cheers, VMG

On Thu, Apr 3, 2014 at 9:22 AM, Laura Hilliger notifications@github.comwrote:

> http://discourse.webmakerprototypes.org
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/p2pu/school-of-webmaking/issues/78#issuecomment-39449842
> .

## 

Vanessa Gennarelli
mozzadrella.me
@mozzadrella
