### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by dirkcuys** [mozilla/school-of-webmaking#85]
We should add a custom 404 page - the current one is rather unhelpful.

**Comment by dirkcuys** [comment]
I added the 404 page (1e907d4ac72183ec2fb427c4382b99f54b65380a), but I think we are missing the config on the Amazon Web Services S3 bucket to serve the file when a 404 happens.

**Comment by LauraHilliger** [comment]
Hrm, I dunno what you're talking about, but maybe @jdotpz can hook us up. He's the MoFo S3 mastermind :)

**Comment by jdotpz** [comment]
Custom 404 page has been added and configured in the S3 bucket.

http://training.webmakerprototypes.org/en/1 now shows the custom 404 page.

**Comment by dirkcuys** [comment]
Thanks @jdotpz !! I'll add the topnav, @LauraHilliger can you please have look at the content for the page?

**Comment by dirkcuys** [comment]
Ok, header is there, so we just need to give a friendly message to users
