### ISSUE TITLE
Global nav should stay highlighted when user is on the page

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#86]
When you click the start here button you're taken to the page and the global nav should stay highlighted.

**Comment by LauraHilliger** [comment]
just noticed it works on modules

**Comment by dirkcuys** [comment]
This should be fixed now. The pages use a special variable in the front matter to set the active tab in the navbar. If this is a bit too tricky we can figure out a different way to set the active tabs.
