### ISSUE TITLE
make webmaker login more visible on Discourse

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#89]
@dirkcuys This:
http://i.imgur.com/i2SLXl5.png
makes it seem like we prefer people use google login over webmaker. Can we make the google grey and use the Webmaker button (perhaps a bit larger, to devalue the google login?):

http://i.imgur.com/r70JuKo.png

**Comment by dirkcuys** [comment]
@LauraHilliger The webmaker login hasn't been 100% resolved. Should we keep on supporting Google logins when that is working?

For the short term I'll look into making it look normal - the greyed out button is a bug.

**Comment by dirkcuys** [comment]
The button doesn't show up as greyed out anymore and webmaker login is working. Should we disable Google logins or leave it there for the moment?

**Comment by LauraHilliger** [comment]
let's leave it, but can we make the webmaker more visually preferred? Like, could we just dim the google login to visually encourage people to sign in with Webmaker (the opposite of how it was before).

**Comment by dirkcuys** [comment]
Ok, I swapped the buttons so that Webmaker comes first and I changed it so that Google is greyed out.
